language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
before_script:
  - gem install license_finder
  - npm install -g mocha
  - npm install -g
script:
  - mocha test
  - ./.travis_test.sh
  - ./ni-self

