language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
before_script:
  - ./script/before_setup.sh
script:
  - ./script/test_setup.sh
after_script: 
  - ./script/after_setup.sh

